import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@repo/ui/globals.css";
import "../styles/main.css";
import PangeaAuthProvider from "@/components/providers/auth-provider";
import Header from "@/components/header";
import { cn } from "@ui/lib/utils";
import Footer from "@/components/footer/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "max-w-[85rem] mx-auto relative")}>
        <PangeaAuthProvider>
          <>
            <Header />
            {children}
            <Footer />
          </>
        </PangeaAuthProvider>
      </body>
    </html>
  );
}
